name: drlfinal
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
    - protobuf==3.20.1
    - termcolor==1.1.0
    - gym==0.22.0
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
